telemetry_base_url: "__SERVER_URL__"
enabled: true
customer_id: "__CUSTOMER_ID__"
tags: []
datastores:
  driver: sqlite3
  params: /tmp/telemetry/client/telemetry.db
logging:
  level: debug
  location: stderr
  style: text
class_options:
  opt_out: true
  opt_in: false
  allow: []
  deny: []
