telemetry_base_url: {{.SERVER_URL}}
enabled: true
customer_id: {{.CUSTOMER_ID}}
tags: []
datastores:
  driver: sqlite3
  params: /tmp/telemetry/client/telemetry.db
logging:
  level: debug
  location: stderr
  style: text
class_options:
  opt_out: true
  opt_in: false
  allow: []
  deny: []
