telemetry_base_url: "http://localhost:9999/telemetry"
enabled: true
customer_id: 1234567890
tags: []
datastores:
  driver: sqlite3
  params: /tmp/telemetry/client/telemetry.db
logging:
  level: info
  location: stderr
  style: text
class_options:
  opt_out: true
  opt_in: false
  allow: []
  deny: []
