telemetry_base_url: "http://localhost:9999/telemetry"
enabled: true
customer_id: 1234567890
tags: []
datastores:
  driver: sqlite3
  params: /tmp/telemetry/client/telemetry.db
extras:
  some: thing
  else:
    - one
    - two
    - three
  or:
    maybe: 2024
logging:
  level: info
  location: stderr
  style: text
