replicas: 1
replicasFilesCount: 10

image:
  repository: gbuenodevsuse/telemetry-client
  tag: test2
  pullPolicy: Always

env:
  serverURL: "http://telemetry-server:9999/telemetry"
  telemetryPath: /app/cmd/faker/fake_telemetry_data
