---

name: Run Pull Request CI Verification

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: registry.suse.com/bci/golang:1.23-openssl

    steps:
      - name: Checkout PR sources
        uses: actions/checkout@v4
        with:
          path: telemetry

      - name: Run tests in verbose mode as non-root testuser
        run: |
          set -eu

          testuser=${TESTUSER:-susetelm}
          echo Creating ${testuser} account
          useradd -m -U -s /bin/bash ${testuser}

          echo Changing ownership of directories accessed by the test
          chown -R ${testuser}:${testuser} telemetry /go

          echo Running tests as ${testuser}: $(id ${testuser})
          cd telemetry
          runuser -u ${testuser} -- make test-verbose
